### ISSUE TITLE
As an employee I will look at a Role and mark an Achievement as accomplished

### ISSUE THREAD

**Issue by Vogete** [gaboratorium/skillsandroles#21]
As an employee I will look at a Role and mark an Achievement as accomplished
[https://drive.google.com/file/d/0B3bphlthkijST3VKeVdkeU42YUU/view?usp=sharing](https://drive.google.com/file/d/0B3bphlthkijST3VKeVdkeU42YUU/view?usp=sharing)

**Comment by zsofitoth** [comment]
Maybe I'll do it on Sunday
